version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: mon_postgres
    restart: always
    environment:
      POSTGRES_USER: prisma_user
      POSTGRES_PASSWORD: prisma_password
      POSTGRES_DB: prisma_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
